# Defines a server that lives indefinitely

platform: vultr

servers:

  # These stacks are required infrastructure and run continuously. They don't
  # utilize many resources and so run on a single machine.
  - label: permanent
    firewall: public
    private-networking: true
    os:
      iso: installcoreos.iso

    ssh-keys:
      - personal

    plan:
      cpu: 1
      memory: 1024
      type: SSD

    region: New Jersey
    userdata:
      stacks:

        # Private NuGet server for hosting C# libraries
        - nuget

        # Keeps the IQFeed server alive to prevent restarting
        - iqfeed-keep-alive
